### ISSUE TITLE
300_trimers.txt

### ISSUE THREAD

**Issue by CaoChensy** [Vini2/CodeForMediumArticles#1]
Hello, I would like to ask, where can I get this file 300_trimers.txt, I read your article "How similar is COVID-19 to previously discovered Coronaviruses",

**Comment by Vini2** [comment]
Hello @CaoChensy,

Thank you for your interest in my Medium articles. I have added the [300_trimers.txt](https://github.com/Vini2/CodeForMediumArticles/blob/master/Coronaviruses/300_trimers.txt) file to the repository.
